export {default as SignUp} from "./SignUp/SignUp";
export {default as Login} from "./Login/Login";
export {default as OTPVerification} from "./OTPVerification/OTPVerification";
export {default as HomePage} from "./HomePage/HomePage"
export {default as Search} from "./Search/Search";
export {default as Charts} from "./Charts/Charts";
export {default as QRCode} from "./QRCode/QRCode";
export {default as Chat} from "./Chat/Chat";
export {default as OneToOneChat} from "./OneToOneChat/OneToOneChat"